apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  namespace: default
  labels:
    app: scaletestapp
spec:
  selector:
    matchLabels:
      app: scaletestapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
        - name: scaletestapp
          image: shestera/scaletestapp
          resources:
            requests:
              cpu: 100m
              memory: "20Mi"
            limits:
              cpu: 500m
              memory: "50Mi"
          ports:
            - containerPort: 8080
              name: http
      restartPolicy: Always
