apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  namespace: default
spec:
  selector:
    app: scaletestapp
  type: ClusterIP
  ports:
    - name: scaletestapp
      protocol: TCP
      port: 8080
      targetPort: 8080
